name: Build and Publish Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker container with Arch Linux
      run: |
        docker run --rm --privileged -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          # Update and install dependencies
          pacman -Syu --noconfirm
          bash install_dependencies.sh
          
          # Build the project
          bash build.sh
        "

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minrescue-isos
        path: dist/
